//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVDump3Lib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVDump3Lib.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused.
        /// </summary>
        internal static string Consumer_CPY_Description {
            get {
                return ResourceManager.GetString("Consumer.CPY.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/Cyclic_redundancy_check.
        /// </summary>
        internal static string Consumer_CRC32_Description {
            get {
                return ResourceManager.GetString("Consumer.CRC32.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castagnoli CRC32 Variant (0x1EDC6F41 Polynomial).
        /// </summary>
        internal static string Consumer_CRC32C_Description {
            get {
                return ResourceManager.GetString("Consumer.CRC32C.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/Ed2k_URI_scheme#eD2k_hash_algorithm.
        /// </summary>
        internal static string Consumer_ED2K_Description {
            get {
                return ResourceManager.GetString("Consumer.ED2K.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/SHA-3.
        /// </summary>
        internal static string Consumer_KECCAK_224_Description {
            get {
                return ResourceManager.GetString("Consumer.KECCAK-224.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/SHA-3.
        /// </summary>
        internal static string Consumer_KECCAK_256_Description {
            get {
                return ResourceManager.GetString("Consumer.KECCAK-256.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/SHA-3.
        /// </summary>
        internal static string Consumer_KECCAK_384_Description {
            get {
                return ResourceManager.GetString("Consumer.KECCAK-384.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/SHA-3.
        /// </summary>
        internal static string Consumer_KECCAK_512_Description {
            get {
                return ResourceManager.GetString("Consumer.KECCAK-512.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/MD4.
        /// </summary>
        internal static string Consumer_MD4_Description {
            get {
                return ResourceManager.GetString("Consumer.MD4.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/MD5.
        /// </summary>
        internal static string Consumer_MD5_Description {
            get {
                return ResourceManager.GetString("Consumer.MD5.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumes Matroska files to provide info for Reports.
        /// </summary>
        internal static string Consumer_MKV_Description {
            get {
                return ResourceManager.GetString("Consumer.MKV.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused.
        /// </summary>
        internal static string Consumer_MP4_Description {
            get {
                return ResourceManager.GetString("Consumer.MP4.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumes data without processing it.
        /// </summary>
        internal static string Consumer_NULL_Description {
            get {
                return ResourceManager.GetString("Consumer.NULL.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumes OGG files to provide info for Reports.
        /// </summary>
        internal static string Consumer_OGG_Description {
            get {
                return ResourceManager.GetString("Consumer.OGG.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/SHA-1.
        /// </summary>
        internal static string Consumer_SHA1_Description {
            get {
                return ResourceManager.GetString("Consumer.SHA1.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/SHA-2.
        /// </summary>
        internal static string Consumer_SHA2_256_Description {
            get {
                return ResourceManager.GetString("Consumer.SHA2-256.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/SHA-2.
        /// </summary>
        internal static string Consumer_SHA2_384_Description {
            get {
                return ResourceManager.GetString("Consumer.SHA2-384.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/SHA-2.
        /// </summary>
        internal static string Consumer_SHA2_512_Description {
            get {
                return ResourceManager.GetString("Consumer.SHA2-512.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/SHA-3.
        /// </summary>
        internal static string Consumer_SHA3_224_Description {
            get {
                return ResourceManager.GetString("Consumer.SHA3-224.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/SHA-3.
        /// </summary>
        internal static string Consumer_SHA3_256_Description {
            get {
                return ResourceManager.GetString("Consumer.SHA3-256.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/SHA-3.
        /// </summary>
        internal static string Consumer_SHA3_384_Description {
            get {
                return ResourceManager.GetString("Consumer.SHA3-384.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/SHA-3.
        /// </summary>
        internal static string Consumer_SHA3_512_Description {
            get {
                return ResourceManager.GetString("Consumer.SHA3-512.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/Tiger_(hash_function).
        /// </summary>
        internal static string Consumer_TIGER_Description {
            get {
                return ResourceManager.GetString("Consumer.TIGER.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org/wiki/Merkle_tree#Tiger_tree_hash.
        /// </summary>
        internal static string Consumer_TTH_Description {
            get {
                return ResourceManager.GetString("Consumer.TTH.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete xml report with every available information node.
        /// </summary>
        internal static string Report_AVD3_Description {
            get {
                return ResourceManager.GetString("Report.AVD3.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matroska Structure Report.
        /// </summary>
        internal static string Report_Matroska_Description {
            get {
                return ResourceManager.GetString("Report.Matroska.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw MediaInfoLibrary Output.
        /// </summary>
        internal static string Report_MediaInfoXml_Description {
            get {
                return ResourceManager.GetString("Report.MediaInfoXml.Description", resourceCulture);
            }
        }
    }
}
