//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVDump3CL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVDump3CL.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular buffer size for hashing.
        /// </summary>
        internal static string BlockSizeDescription {
            get {
                return ResourceManager.GetString("BlockSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --BSize=&lt;blocksize in MiB&gt;:&lt;block count&gt;.
        /// </summary>
        internal static string BlockSizeExample {
            get {
                return ResourceManager.GetString("BlockSizeExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the maximal number of files which will be processed concurrently.
        ///First param (max) sets a global limit. (path,max) pairs sets limits per path..
        /// </summary>
        internal static string ConcurrentDescription {
            get {
                return ResourceManager.GetString("ConcurrentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Concurrent=&lt;max&gt;[:&lt;path1&gt;,&lt;max1&gt;;&lt;path2&gt;,&lt;max2&gt;;...].
        /// </summary>
        internal static string ConcurrentExample {
            get {
                return ResourceManager.GetString("ConcurrentExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select consumers to use. See --ListConsumers for available consumers.
        /// </summary>
        internal static string ConsumersDescription {
            get {
                return ResourceManager.GetString("ConsumersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Consumers=&lt;ConsumerName1&gt;[,&lt;ConsumerName2&gt;,...].
        /// </summary>
        internal static string ConsumersExample {
            get {
                return ResourceManager.GetString("ConsumersExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ErrorDirectoryDescription {
            get {
                return ResourceManager.GetString("ErrorDirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ErrorDirectoryExample {
            get {
                return ResourceManager.GetString("ErrorDirectoryExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HideBuffersDescription {
            get {
                return ResourceManager.GetString("HideBuffersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HideBuffersExample {
            get {
                return ResourceManager.GetString("HideBuffersExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HideFileProgressDescription {
            get {
                return ResourceManager.GetString("HideFileProgressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HideFileProgressExample {
            get {
                return ResourceManager.GetString("HideFileProgressExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HideTotalProgressDescription {
            get {
                return ResourceManager.GetString("HideTotalProgressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HideTotalProgressExample {
            get {
                return ResourceManager.GetString("HideTotalProgressExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IncludePersonalDataDescription {
            get {
                return ResourceManager.GetString("IncludePersonalDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IncludePersonalDataExample {
            get {
                return ResourceManager.GetString("IncludePersonalDataExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PrintHashesDescription {
            get {
                return ResourceManager.GetString("PrintHashesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PrintHashesExample {
            get {
                return ResourceManager.GetString("PrintHashesExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PrintReportsDescription {
            get {
                return ResourceManager.GetString("PrintReportsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PrintReportsExample {
            get {
                return ResourceManager.GetString("PrintReportsExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursively descent into Subdirectories.
        /// </summary>
        internal static string RecursiveDescription {
            get {
                return ResourceManager.GetString("RecursiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Recursive.
        /// </summary>
        internal static string RecursiveExample {
            get {
                return ResourceManager.GetString("RecursiveExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select reports to use. See --ListReports for available reports.
        /// </summary>
        internal static string ReportsDescription {
            get {
                return ResourceManager.GetString("ReportsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Reports.
        /// </summary>
        internal static string ReportsExample {
            get {
                return ResourceManager.GetString("ReportsExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SkipEnvironmentElementDescription {
            get {
                return ResourceManager.GetString("SkipEnvironmentElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SkipEnvironmentElementExample {
            get {
                return ResourceManager.GetString("SkipEnvironmentElementExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only/Don&apos;t Process files with selected Extensions.
        /// </summary>
        internal static string WithExtensionsDescription {
            get {
                return ResourceManager.GetString("WithExtensionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --WithExtensions=[-]&lt;Extension1&gt;[,&lt;Extension2&gt;,...].
        /// </summary>
        internal static string WithExtensionsExample {
            get {
                return ResourceManager.GetString("WithExtensionsExample", resourceCulture);
            }
        }
    }
}
