//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVDump3GUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVDump3GUI.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cursor position of the console will not be explicitly set. This option will disable most progress output.
        /// </summary>
        internal static string Display_ForwardConsoleCursorOnly_Description {
            get {
                return ResourceManager.GetString("Display.ForwardConsoleCursorOnly.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --ForwardConsoleCursorOnly.
        /// </summary>
        internal static string Display_ForwardConsoleCursorOnly_Example {
            get {
                return ResourceManager.GetString("Display.ForwardConsoleCursorOnly.Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides buffer bars.
        /// </summary>
        internal static string Display_HideBuffers_Description {
            get {
                return ResourceManager.GetString("Display.HideBuffers.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --HideBuffers.
        /// </summary>
        internal static string Display_HideBuffers_Example {
            get {
                return ResourceManager.GetString("Display.HideBuffers.Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides file progress.
        /// </summary>
        internal static string Display_HideFileProgress_Description {
            get {
                return ResourceManager.GetString("Display.HideFileProgress.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --HideFileProgress.
        /// </summary>
        internal static string Display_HideFileProgress_Example {
            get {
                return ResourceManager.GetString("Display.HideFileProgress.Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides total progress.
        /// </summary>
        internal static string Display_HideTotalProgress_Description {
            get {
                return ResourceManager.GetString("Display.HideTotalProgress.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --HideTotalProgress.
        /// </summary>
        internal static string Display_HideTotalProgress_Example {
            get {
                return ResourceManager.GetString("Display.HideTotalProgress.Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the time taken to calculate progression stats and drawing to console.
        /// </summary>
        internal static string Display_ShowDisplayJitter_Description {
            get {
                return ResourceManager.GetString("Display.ShowDisplayJitter.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --ShowDisplayJitter.
        /// </summary>
        internal static string Display_ShowDisplayJitter_Example {
            get {
                return ResourceManager.GetString("Display.ShowDisplayJitter.Example", resourceCulture);
            }
        }
    }
}
