name: AVDump3

env:
  AVD3Configuration: Release

on:
  push:
    branches: [ master, AVD3Workflow-Testing ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        include: 
          - os: windows-latest
            platform: windows
          - os: ubuntu-latest
            platform: linux
        
        
    steps:
      - name: AVD3Checkout
        uses: actions/checkout@v2.1.0
      - name: AVD3LinuxCompile
        if: matrix.platform == 'linux'
        run: |
          ls -lhR $GITHUB_WORKSPACE
          
          mkdir AVDump3NativeLib/obj/
          mkdir AVDump3NativeLib/bin/
          cd AVDump3NativeLib/obj/        
          gcc -mavx -mavx2 -msse4 -msha -O3 -c -Wall -Werror -fpic $GITHUB_WORKSPACE/AVDump3NativeLib/*.c -lrt 
          cd ../..
          
          gcc -mavx -mavx2 -msse4 -msha -O3 -shared -o $GITHUB_WORKSPACE/AVDump3NativeLib/bin/AVDump3NativeLib.so $GITHUB_WORKSPACE/AVDump3NativeLib/obj/*.o -lrt
          
      - name: AVD3LinuxArtifactUpload
        if: matrix.platform == 'linux'
        uses: actions/upload-artifact@v2
        with:
          name: AVDump3NativeLib.so
          path: ${{ GITHUB_WORKSPACE }}/AVDump3NativeLib/bin/AVDump3NativeLib.so
        
  
