name: AVDump3

on:
  push:
    tags: [ 'v*' ]
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-avd3-native:
    name: build-avd3-native/${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        include: 
        - os: windows-latest
          platform: windows
        - os: ubuntu-latest
          platform: linux
          
    steps:
    - name: AVD3Native-Checkout
      uses: actions/checkout@v2.1.0

    - name: AVD3Native-Compile-Linux
      if: matrix.platform == 'linux'
      run: |         
        mkdir AVDump3NativeLib/obj/
        mkdir AVDump3NativeLib/bin/
        cd AVDump3NativeLib/obj/        
        gcc -mavx -mavx2 -msse4 -msha -O3 -c -Wall -Werror -fpic $GITHUB_WORKSPACE/AVDump3NativeLib/*.c -lrt 
        cd ../..

        gcc -mavx -mavx2 -msse4 -msha -O3 -shared -o $GITHUB_WORKSPACE/AVDump3NativeLib/bin/AVDump3NativeLib.so $GITHUB_WORKSPACE/AVDump3NativeLib/obj/*.o -lrt

    - name: AVD3Native-ArtifactUpload-Linux
      if: matrix.platform == 'linux'
      uses: actions/upload-artifact@v2
      with:
        name: AVDump3NativeLib.Linux
        path: ${{ github.workspace }}/AVDump3NativeLib/bin/AVDump3NativeLib.so


    - name: AVD3Native-MSBuildSetup-Windows
      if: matrix.platform == 'windows'
      uses: microsoft/setup-msbuild@v1.0.0

    - name: AVD3Native-Compile-Windows
      if: matrix.platform == 'windows'
      run: |
        msbuild AVDump3.sln /t:AVDump3NativeLib /p:Configuration="GithubWorkflow" /p:Platform="x64" /p:BuildProjectReferences=false

    - name: AVD3Native-ArtifactUpload-Windows
      if: matrix.platform == 'windows'
      uses: actions/upload-artifact@v2
      with:
        name: AVDump3NativeLib.Windows
        path: ${{ github.workspace }}\AVDump3NativeLib\x64\GithubWorkflow\AVDump3NativeLib.dll

  build-avd3-main:
    needs: build-avd3-native
    runs-on: ubuntu-latest
    steps:
    - name: AVD3Main-Checkout
      uses: actions/checkout@v2
      
    - name: AVD3Main-DotNetSetup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102

    - name: AVD3Main-DownloadArtifacts
      uses: actions/download-artifact@v2
      with:
        path: ${{ github.workspace }}/AVDump3CL/bin/GithubWorkflow/netcoreapp3.1/
    
    - name: AVDMain-MoveArtifacts
      run: |
        find $GITHUB_WORKSPACE/AVDump3CL/bin/GithubWorkflow/netcoreapp3.1/ -type f -print -exec mv {} $GITHUB_WORKSPACE/AVDump3CL/bin/GithubWorkflow/netcoreapp3.1/ \;
        rm -R -- $GITHUB_WORKSPACE/AVDump3CL/bin/GithubWorkflow/netcoreapp3.1/*/
    
    - name: AVD3Main-Compile
      run: dotnet build --configuration GithubWorkflow        
      
    - name: AVD3Main-CopyLibs  
      run: |
        cp $GITHUB_WORKSPACE/AVDump3Lib/Libs/MediaInfo.* $GITHUB_WORKSPACE/AVDump3CL/bin/GithubWorkflow/netcoreapp3.1/
      
    - name: AVD3Main-ArtifactUpload
      uses: actions/upload-artifact@v2
      with:
        name: AVDump3CL
        path: ${{ github.workspace }}/AVDump3CL/bin/GithubWorkflow/netcoreapp3.1/

  release-avd3-main:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build-avd3-main

    steps:
    - name: AVD3Release-Create
      id: avd3releasecreate
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

    - name: AVD3Release-DownloadArtifacts
      uses: actions/download-artifact@v2
      with:
        name: AVDump3CL
        path: ${{ github.workspace }}/AVDump3CL.zip

    - name: AVD3Release-UploadAsset
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.avd3releasecreate.outputs.upload_url }}
        asset_path:  ${{ github.workspace }}/AVDump3CL.zip
        asset_name: ${{ github.ref }}
        asset_content_type: application/zip
