name: AVDump3

env:
  AVD3Configuration: Release

on:
  push:
    branches: [ master, AVD3Workflow-Testing ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        include: 
          - os: windows-latest
            platform: windows
          - os: ubuntu-latest
            platform: linux
        
        
    steps:
      - name: AVD3Checkout
        uses: actions/checkout@v2.1.0
      - name: AVD3CompileLinux
        if: matrix.platform == 'linux'
        run: |
          pwd
          ls -Rlh
          gcc -c -Wall -Werror -fpic -msha -O3 $GITHUB_WORKSPACE/AVDump3NativeLib/*.c -lrt 
          gcc -msha -O3 -shared -o $GITHUB_WORKSPACE/AVDump3NativeLib.so $GITHUB_WORKSPACE/AVDump3NativeLib/*.o -lrt
        
        
  
